spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bloom
    username: postgres
    password: password
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  error:
    include-stacktrace: never
    include-message: always
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
management:
  endpoints:
    web:
      exposure:
        include:
          - "health"
          - "metrics"
bloom:
  notification-queue-name: notification
