spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bloom-testing
server:
  disable-cors: true
  error:
    include-stacktrace: never
    include-message: always
