spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:60000/bloom-testing
    username: postgres
    password: password
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  error:
    include-stacktrace: never
    include-message: always
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
bloom:
  mq:
    queue: whistle