spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/bloom-testing
server:
  error:
    include-stacktrace: never
    include-message: always
