spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:60001/bloom
server:
  error:
    include-stacktrace: never
    include-message: always
