spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://db-postgres:5432/bloom
    username: postgres
    password: password
  rabbitmq:
    host: mq-rabbit
    port: 5672
    username: guest
    password: guest
