# Deployment containing the full application and services

services:
  bloom-main:
    build: ../bloom-main
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bloom
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
