# Deployment containing the full application and services
name: bloom
services:
  bloom-main:
    build: ../bloom-main
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq
  bloom-webapp:
    build: ../bloom-webapp
    ports:
      - "3000:3000"
    depends_on:
      - bloom-main
    environment:
        - API_BASE_URL=http://bloom-main:8080
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bloom
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
